### ISSUE TITLE
where to get hwacha ISA spec 

### ISSUE THREAD

**Issue by ShuyunJia** [ucb-bar/esp-tools#2]
Hi,
I'm looking at this hwacha project and want to further develop it.   

I can get some basic description of this ISA from the `UCB-EECS-2015-262 technical report`, which only categorizes instructions and describes the decoding of each.  

I would like to know where to get documentations on further descriptions of each instructions.   

-Shuyun

**Comment by a0u** [comment]
There isn't a more detailed ISA document, unfortunately.  Besides the pseudocode in that tech report, the closest source of individual instruction semantics is the spike model.

https://github.com/ucb-bar/esp-isa-sim/tree/master/hwacha/insns
https://github.com/ucb-bar/esp-isa-sim/tree/master/hwacha/insns_ut

**Comment by ShuyunJia** [comment]
Thanks, issue closed.
